package com.mandate.common;

import lombok.Getter;

@Getter
public enum BankType {

	IDFC_BANK("IDFC Bank"),
	IDBI_BANK("IDBI BANK"),
	TAMILNADU_MERCANTILE_BANK("Tamilnad Mercantile Bank"),
	THE_CATHOLIC_SYRIAN_BANK("THE CATHOLIC SYRIAN BANK"),
	BANDHAN_BANK_LTD("BANDHAN BANK LTD"),
	PUNJAB_NATIONAL_BANK("Punjab National Bank"),
	UJJIVAN_SMALL_FINANCE_BANK("Ujjivan Small Finance Bank"),
	BANK_OF_MAHARASTRA("Bank of Maharashtra"),
	STANDARD_CHARTERED_BANK("Standard Chartered Bank"),
	THE_COSMOS_CO_OPERATIVE_BANK("The Cosmos Co-Operative Bank"),
	UCO_BANK("UCO Bank"),
	AXIS_BANK("Axis Bank"),
	YES_BANK("Yes Bank"),
	RBL_BANK("RBL BANK"),
	HDFC_BANK_LTD("HDFC BANK LTD"),
	PAYTM_PAYMENTS_BANK("Paytm Payments Bank"),
	THE_JAMMU_AND_KASHMIR_BANK_LTD("THE JAMMU AND KASHMIR BANK LTD"),
	THE_VARACHHA_CO_OP_BANK_LTD("THE VARACHHA CO OP BANK LTD"),
	DBS_BANK_INDIA_LTD("DBS Bank India Ltd"),
	JANA_SMALL_FINANCE_BANK_LTD("JANA SMALL FINANCE BANK LTD"),
	KARNATAKA_BANK_LTD("KARNATAKA BANK LTD"),
	SOUTH_INDIAN_BANK("South Indian Bank"),
	INDIAN_BANK("INDIAN BANK"),
	KARNATKA_VIKAS_GRAMEENA_BANK("KARNATAKA VIKAS GRAMEENA BANK"),
	CENTRAL_BANK_OF_INDIA("Central Bank of India"),
	STATE_BANK_OF_INDIA("State Bank of India"),
	KOTAK_MAHINDRA_BANK("Kotak Mahindra Bank"),
	UNION_BANK_OF_INDIA("Union Bank of India"),
	DCB_BANK_LTD("DCB BANK LTD"),
	AIRTEL_PAYMENTS_BANK_LTD("AIRTEL PAYMENTS BANK LTD"),
	DEUTSCHE_BANK("Deutsche Bank"),
	EQUITAS_SMALL_FINANCE_BANK("Equitas Small Finance Bank"),
	DHANALAXMI_BANK("Dhanalaxmi Bank"),
	CANARA_BANK("Canara Bank"),
	ANDHRA_PRAGATHI_GRAMEENA_BANK("ANDHRA PRAGATHI GRAMEENA BANK"),
	BANK_OF_BARODRA("Bank of Baroda"),
	INDIAN_OVERSEAS_BANK("Indian Overseas Bank"),
	CITY_UNION_BANK("City Union Bank"),
	ESAF_SMALL_FINANCE_BANK_LTD("ESAF SMALL FINANCE BANK LTD"),
	INDUS_IND_BANK("INDUS IND Bank"),
	SBM_BANK_INDIA_LTD("SBM BANK INDIA LTD"),
	FEDERAL_BANK("Federal Bank"),
	PUNJAB_AND_SIND_BANK("PUNJAB AND SIND BANK"),
	JIO_PAYMENTS_BANK_LTD("JIO PAYMENTS BANK LTD"),
	CITI_BANK("CITI BANK"),
	KARUR_VYSA_BANK("KARUR VYSA BANK"),
	HSBC("HSBC"),
	AU_SMALL_FINANCE_BANK("AU SMALL FINANCE BANK");
	
	private String bank;
	BankType(String string) {
		this.bank=string;
	}
}
